#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const readline = require('readline/promises');

const serverRoot = path.resolve(__dirname, '..');
const envPath = path.join(serverRoot, '.env');

const fields = [
  {
    key: 'APP_PASSWORD',
    label: 'App password for the UI login',
    secret: true,
    required: true,
  },
  {
    key: 'GCP_PROJECT_ID',
    label: 'Google Cloud project ID',
    required: true,
    example: 'my-gcp-project',
  },
  {
    key: 'GCP_LOCATION',
    label: 'Dialogflow CX location',
    required: true,
    example: 'europe-west1',
  },
  {
    key: 'DIALOGFLOW_AGENT_ID',
    label: 'Dialogflow CX agent ID',
    required: true,
    example: '00000000-0000-0000-0000-000000000000',
  },
  {
    key: 'GOOGLE_APPLICATION_CREDENTIALS',
    label: 'Path to local Google service account JSON',
    required: true,
    example: './credentials/service-account.json',
    validate(value) {
      const resolved = path.resolve(serverRoot, value);
      if (!fs.existsSync(resolved)) {
        return `File not found: ${resolved}`;
      }
      return null;
    },
  },
];

function parseArgs() {
  const args = new Set(process.argv.slice(2));
  return {
    check: args.has('--check'),
    noPrompt: args.has('--no-prompt') || args.has('--ci'),
  };
}

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};

  return fs.readFileSync(filePath, 'utf8')
    .split(/\r?\n/)
    .reduce((env, line) => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) return env;

      const match = trimmed.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
      if (!match) return env;

      let value = match[2].trim();
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1);
      }
      env[match[1]] = value.replace(/\\n/g, '\n');
      return env;
    }, {});
}

function quoteEnv(value) {
  return JSON.stringify(value);
}

function buildEnvFile(values) {
  const lines = [
    '# Local server configuration.',
    '# This file is generated by npm run setup and must not be committed.',
    '',
  ];

  for (const field of fields) {
    lines.push(`${field.key}=${quoteEnv(values[field.key] || '')}`);
  }

  lines.push('', '# Optional overrides', 'PORT="3001"', 'DATA_DIR="../data/sessions"', '');
  return lines.join('\n');
}

function getMissing(values) {
  return fields.filter((field) => field.required && !values[field.key]);
}

function validate(values) {
  const errors = [];

  for (const field of fields) {
    if (field.required && !values[field.key]) {
      errors.push(`${field.key} is required.`);
      continue;
    }

    if (values[field.key] && field.validate) {
      const error = field.validate(values[field.key]);
      if (error) errors.push(`${field.key}: ${error}`);
    }
  }

  return errors;
}

function printSetupInstructions(errors = []) {
  if (errors.length) {
    console.error('Server setup is incomplete:');
    for (const error of errors) {
      console.error(`- ${error}`);
    }
    console.error('');
  }

  console.error('Run this from the server directory to create a local .env file:');
  console.error('  npm run setup');
  console.error('');
  console.error('Keep the service account JSON outside source control, for example:');
  console.error('  server/credentials/service-account.json');
}

async function promptForValues(existing) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const values = { ...existing };

  try {
    console.log('Server first-run setup');
    console.log('Values are written to server/.env, which is ignored by git.');
    console.log('');

    for (const field of fields) {
      while (true) {
        const current = values[field.key];
        const hint = current
          ? field.secret ? ' [currently set]' : ` [${current}]`
          : field.example ? ` (${field.example})` : '';
        const answer = await rl.question(`${field.label}${hint}: `);
        const next = answer.trim() || current || '';
        values[field.key] = next;

        const errors = validate({ ...values, [field.key]: next })
          .filter((error) => error.startsWith(`${field.key}:`) || error.startsWith(`${field.key} `));

        if (!errors.length) break;
        console.error(errors.join('\n'));
      }
    }
  } finally {
    rl.close();
  }

  return values;
}

async function main() {
  const args = parseArgs();
  const existing = parseEnvFile(envPath);
  const errors = validate(existing);

  if (args.check && errors.length === 0) {
    return;
  }

  if (args.noPrompt || !process.stdin.isTTY || !process.stdout.isTTY) {
    printSetupInstructions(errors);
    process.exit(1);
  }

  if (args.check && getMissing(existing).length === 0 && errors.length > 0) {
    printSetupInstructions(errors);
    process.exit(1);
  }

  const values = await promptForValues(existing);
  const finalErrors = validate(values);
  if (finalErrors.length) {
    printSetupInstructions(finalErrors);
    process.exit(1);
  }

  fs.writeFileSync(envPath, buildEnvFile(values), { mode: 0o600 });
  console.log('');
  console.log(`Wrote ${path.relative(process.cwd(), envPath)}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
